### ISSUE TITLE
Could this Mod adjust the Processor Block `maxInstructions = 1000;` limit?

### ISSUE THREAD

**Issue by schittli** [sk7725/Commands#3]
Hello

Thank you **very much** for your Commands Mod!

I have a question:
because Mindustry declares `public static final int maxInstructions = 1000;`, Processor Blocks can have max. 1000 Commands. `maxInstructions` is declared here in `LExecutor.java`:

[https://github.com/Anuken/Mindustry/search?q=maxInstructions](https://github.com/Anuken/Mindustry/search?q=maxInstructions)

Would it possible to adjust `maxInstructions` in a Mod?

Thanks a lot, kind regards,
Thomas

**Comment by tezlm** [comment]
```java
    public static final int maxInstructions = 1000;
```
unfortunately its a final int, so it can't be changed. even if you used reflection or something, 

![image](https://user-images.githubusercontent.com/56274831/113461721-93fa4600-93d2-11eb-9261-7161848c6791.png)
